### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by gmalinve** [ansys/magnet-segmentation-toolkit#140]
- [x] Finish to work on PR #137 (do not merge) @gmalinve 
- [x] Finish to work on PR #135 (to merge) @SMoraisAnsys 
- [x] Specify requirements somewhere (maybe a README) -> SymmetryMultiplier, HalfAxial, Shaft name etc @gmalinve (#142)
- [x] Update documentation (API reference, UI reference, Getting started) -> Delete all references to Motor-CAD + update props @gmalinve 
- [x] Update examples -> Delete all references to Motor-CAD + update props @gmalinve 
- [x] Rename toolkit @gmalinve @SMoraisAnsys (#143)
- [x] New release @gmalinve @SMoraisAnsys 
- [x] Improve tests @gmalinve 
- [x] Get approval for open sourcing @gmalinve - @SMoraisAnsys
